apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
rules:
{{- range .Values.config.resourcesToScan }}
  - apiGroups:
      - "{{ .group }}"
    resources:
      - "{{ if eq .kind "Endpoints" }}{{ .kind | lower }}{{ else if eq .kind "NetworkPolicy"}}{{ "networkpolicies" }}{{ else if eq .kind "Ingress"}}{{ .kind | lower }}es{{ else if eq .kind "StorageClass"}}{{ "storageclasses" }}{{ else }}{{ .kind | lower }}s{{ end }}"
    verbs:
      - get
      - list
      - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "kubernetes-agent.fullname" .) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubernetes-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
