apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    cyscaleAPIBaseURL: {{.Values.config.cyscaleAPIBaseURL | quote}}
    httpClientTimeout: {{.Values.config.httpClientTimeout | quote}}
    resourcesToScan: {{- toYaml .Values.config.resourcesToScan | nindent 4 }}
    cyscaleAPIKey: {{.Values.config.cyscaleAPIKey | quote}}
