name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
      - name: Generate the next version
        uses: cycjimmy/semantic-release-action@v4
        id: release
        with:
          extra_plugins: |
            @semantic-release/git
            semantic-release-helm3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
